OBJS = SumOfIntegers.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

SumOfIntegers : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o SumOfIntegers

SumOfIntegers.o : SumOfIntegers.cpp
			 $(CC) $(CFLAGS) SumOfIntegers.cpp
			 
clean:
	\rm *.o *~ SumOfIntegers